# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Hello, world!
    echo "Hello, World" > toto.txt
  displayName: 'Write text on toto.txt'

- script: echo Hello, world 2!
  displayName: 'Hello world 2'

- script: curl "https://youtube.com"
  displayName: 'Curl youtube'

- script: |
    ls -l
    echo Add other tasks to build, test, and deploy your project.
    cat toto.txt
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
